# Site settings
title: Michael Bigelow Music
email: mb@michaelbigelowmusic.com
description: ""
baseurl: ""
url: "http://www.michaelbigelowmusic.com"

# Build settings
markdown: kramdown
permalink: pretty

social-links:
    - name: facebook
      url: https://www.facebook.com/michaelbigelowmusic
    - name: soundcloud
      url: https://soundcloud.com/michaelbigelowmusic
    - name: youtube
      url: https://www.youtube.com/channel/UCywVyycVrct3mnQN8c30W3A
    - name: linkedin
      url: https://www.linkedin.com/profile/view?id=ADEAAAMBUncBKYSPm9YeOL8QzSPlyhVMtVE9d3c
    - name: googleplus
      url: https://plus.google.com/+MichaelBigelowMusic

nav-pages: 
    - name: Performance
      url: /saxophones/
      icon: icon-saxophone.html
    - name: Composition & Arranging
      url: /composition-arranging/
      icon: icon-note.html
    - name: Instruction
      url: /music-instruction/
      icon: icon-speech.html
