# Site settings
title: Michael Bigelow Music
email: mb@michaelbigelowmusic.com
description: ""
baseurl: ""
url: "michaelbigelowmusic.com"

# Build settings
markdown: kramdown
permalink: pretty

page: 
    - name: saxophones
      url: www.google.com
    - name: music composition
      url: www.yahoo.com