# Site settings
title: Michael Bigelow Music
email: mb@michaelbigelowmusic.com
description: ""
baseurl: ""
url: "michaelbigelowmusic.com"

# Build settings
markdown: kramdown
permalink: pretty

social-links:
    - name: facebook
      url: http://www.facebook.com/
    - name: soundcloud
      url: http://www.soundcloud.com/
    - name: youtube
      url: http://www.youtube.com/ 
    - name: linkedin
      url: http://www.linkedin.com/ 
    - name: googleplus
      url: http://www.googleplus.com/ 

nav-pages: 
    - name: Saxophones
      url: saxophones
    - name: Composition & Arranging
      url: composition-arranging
    - name: Music Instruction
      url: music-instruction
      